//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem
{
    public partial class EditStudent
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.HiddenField hdnStudentId;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        protected global::System.Web.UI.WebControls.TextBox txtCourse;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCourse;

        protected global::System.Web.UI.WebControls.TextBox txtAge;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAge;

        protected global::System.Web.UI.WebControls.RangeValidator rvAge;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
